SET(Local
	Component.h
	ComponentStack.h
	ComponentStack.cpp
	ComponentStackWidget.h
	Template.h
	Template.cpp
	TwoStateControl.h
	WidgetBase.h
	WidgetBase.cpp
	WidgetContainer.h
	WidgetContainer.cpp
	Window.h
)
