SET(Local
	Component.h
	ComponentStack.h
	ComponentStack.cpp
	ComponentStackWidget.h
	Dimension.h
	Helpers.h
	LayerAdapter.h
	LayerAdapter.cpp
	Organizers
	RadioControl.h
	Template.h
	Template.cpp
	../UI.h
	UI.cpp
	TwoStateControl.h
	Validators.h
	Widget.h
	Widget.cpp
	WidgetContainer.h
	WidgetContainer.cpp
	Window.h
	Window.cpp
)
