SET(Local
	Component.h
	ComponentStack.h
	ComponentStack.cpp
	ComponentStackWidget.h
	Helpers.h
	Organizers
	RadioControl.h
	Template.h
	Template.cpp
	../UI.h
	UI.cpp
	TwoStateControl.h
	Validators.h
	WidgetBase.h
	WidgetBase.cpp
	WidgetContainer.h
	WidgetContainer.cpp
	Window.h
)
