# CMake generated Testfile for 
# Source directory: /home/Josey/Documents/Gorgon
# Build directory: /home/Josey/Documents/Gorgon/build-tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[Enum]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-Enum")
set_tests_properties([=[Enum]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
add_test([=[Event]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-Event")
set_tests_properties([=[Event]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
add_test([=[Filesystem]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-Filesystem")
set_tests_properties([=[Filesystem]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
add_test([=[FLAC]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-FLAC")
set_tests_properties([=[FLAC]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
add_test([=[GarbageCollection]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-GarbageCollection")
set_tests_properties([=[GarbageCollection]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
add_test([=[Geometry]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-Geometry")
set_tests_properties([=[Geometry]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
add_test([=[Path]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-Path")
set_tests_properties([=[Path]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
add_test([=[Hashmap]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-Hashmap")
set_tests_properties([=[Hashmap]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
add_test([=[KeyRepeater]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-KeyRepeater")
set_tests_properties([=[KeyRepeater]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
add_test([=[Layer]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-Layer")
set_tests_properties([=[Layer]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
add_test([=[Logging]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-Logging")
set_tests_properties([=[Logging]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
add_test([=[EncodingImage]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-EncodingImage")
set_tests_properties([=[EncodingImage]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
add_test([=[Property]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-Property")
set_tests_properties([=[Property]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
add_test([=[Scene]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-Scene")
set_tests_properties([=[Scene]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
add_test([=[ScopeGuard]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-ScopeGuard")
set_tests_properties([=[ScopeGuard]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
add_test([=[String]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-String")
set_tests_properties([=[String]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
add_test([=[URI]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-URI")
set_tests_properties([=[URI]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
add_test([=[IO]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-IO")
set_tests_properties([=[IO]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
add_test([=[Scripting]=] "/home/Josey/Documents/Gorgon/Testing/Tests/Unit/UnitTest-Scripting")
set_tests_properties([=[Scripting]=] PROPERTIES  WORKING_DIRECTORY "/home/Josey/Documents/Gorgon/Testing/Runtime" _BACKTRACE_TRIPLES "/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;32;ADD_TEST;/home/Josey/Documents/Gorgon/Scripts/Testing.cmake;0;;/home/Josey/Documents/Gorgon/CMakeLists.txt;226;include;/home/Josey/Documents/Gorgon/CMakeLists.txt;0;")
subdirs("Tools/ShaderEmbedder")
