# CMake generated Testfile for 
# Source directory: C:/Users/cengiz/Desktop/gorgon
# Build directory: C:/Users/cengiz/Desktop/gorgon/Tools/Resource-cli/Gorgon
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Enum "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Enum")
  set_tests_properties(Enum PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Enum "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Enum")
  set_tests_properties(Enum PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Enum "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Enum")
  set_tests_properties(Enum PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Enum "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Enum")
  set_tests_properties(Enum PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
else()
  add_test(Enum NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Event "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Event")
  set_tests_properties(Event PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Event "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Event")
  set_tests_properties(Event PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Event "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Event")
  set_tests_properties(Event PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Event "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Event")
  set_tests_properties(Event PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
else()
  add_test(Event NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Filesystem "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Filesystem")
  set_tests_properties(Filesystem PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Filesystem "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Filesystem")
  set_tests_properties(Filesystem PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Filesystem "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Filesystem")
  set_tests_properties(Filesystem PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Filesystem "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Filesystem")
  set_tests_properties(Filesystem PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
else()
  add_test(Filesystem NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GarbageCollection "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-GarbageCollection")
  set_tests_properties(GarbageCollection PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(GarbageCollection "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-GarbageCollection")
  set_tests_properties(GarbageCollection PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(GarbageCollection "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-GarbageCollection")
  set_tests_properties(GarbageCollection PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(GarbageCollection "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-GarbageCollection")
  set_tests_properties(GarbageCollection PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
else()
  add_test(GarbageCollection NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Geometry "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Geometry")
  set_tests_properties(Geometry PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Geometry "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Geometry")
  set_tests_properties(Geometry PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Geometry "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Geometry")
  set_tests_properties(Geometry PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Geometry "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Geometry")
  set_tests_properties(Geometry PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
else()
  add_test(Geometry NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Hashmap "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Hashmap")
  set_tests_properties(Hashmap PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Hashmap "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Hashmap")
  set_tests_properties(Hashmap PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Hashmap "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Hashmap")
  set_tests_properties(Hashmap PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Hashmap "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Hashmap")
  set_tests_properties(Hashmap PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
else()
  add_test(Hashmap NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(String "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-String")
  set_tests_properties(String PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(String "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-String")
  set_tests_properties(String PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(String "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-String")
  set_tests_properties(String PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(String "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-String")
  set_tests_properties(String PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
else()
  add_test(String NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Scripting "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Scripting")
  set_tests_properties(Scripting PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Scripting "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Scripting")
  set_tests_properties(Scripting PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Scripting "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Scripting")
  set_tests_properties(Scripting PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Scripting "C:/Users/cengiz/Desktop/gorgon/Testing/Tests/Unit/UnitTest-Scripting")
  set_tests_properties(Scripting PROPERTIES  WORKING_DIRECTORY "C:/Users/cengiz/Desktop/gorgon/Testing/Runtime")
else()
  add_test(Scripting NOT_AVAILABLE)
endif()
