find_path(OGG_INC ogg/ogg.h)
find_path(VORBIS_INC vorbis/vorbisfile.h)

find_library(OGG_LIB NAMES ogg)
find_library(VORBIS_LIB NAMES vorbis)
find_library(VORBISFILE_LIB NAMES vorbisfile)
find_library(VORBISENC_LIB NAMES vorbisenc)
set(VORBIS_LIBRARIES ${VORBISENC_LIB} ${VORBISFILE_LIB} ${VORBIS_LIB} ${OGG_LIB})

set(VORBIS_INCLUDE_DIRS ${OGG_INC} ${VORBIS_INC})

mark_as_advanced(VORBIS_LIBRARIES VORBIS_INCLUDE_DIRS OGG_INC VORBIS_INC OGG_LIB VORBIS_LIB VORBISFILE_LIB VORBISENC_LIB)
