cmake_minimum_required(VERSION 2.8)


ADD_LIBRARY(GGE STATIC IMPORTED)

SET_PROPERTY(TARGET GGE PROPERTY IMPORTED_LOCATION "${CMAKE_CURRENT_LIST_DIR}/../Lib/libGGE.a")

FIND_PACKAGE(OpenGL REQUIRED)
FIND_PACKAGE (Threads REQUIRED)

MACRO(LinkGGE target)

TARGET_LINK_LIBRARIES(${target} GGE)
TARGET_LINK_LIBRARIES(${target} ${OPENGL_LIBRARIES})
TARGET_LINK_LIBRARIES(${target} X11)
TARGET_LINK_LIBRARIES(${target} openal)
TARGET_LINK_LIBRARIES(${target} ${CMAKE_THREAD_LIBS_INIT})

ENDMACRO()
