CMAKE_MINIMUM_REQUIRED(VERSION 2.8)

MACRO(DoSource)
	IF(${wd} MATCHES ".+")
		MESSAGE("> Building ${wd}")
	ELSE()
		MESSAGE("> Building Root")
	ENDIF()
	
	STRING(REGEX REPLACE "/" "\\\\" srcgrp "${wd}")
	STRING(REGEX REPLACE "Source" "" srcgrp "${srcgrp}")
	STRING(REGEX REPLACE "^\\\\" "" srcgrp "${srcgrp}")
	
	IF(${wd} MATCHES ".+")
		SET(LocalFixed)
		FOREACH(L ${Local}) 
			IF(IS_DIRECTORY "${CMAKE_SOURCE_DIR}/${wd}/${L}")
			ELSE()
				LIST(APPEND LocalFixed "${wd}/${L}")
			ENDIF()
		ENDFOREACH()
	ELSE()
		SET(LocalFixed)
		FOREACH(L ${Local}) 
			IF(IS_DIRECTORY "${CMAKE_SOURCE_DIR}/${wd}/${L}")
			ELSE()
				LIST(APPEND LocalFixed ${L})
			ENDIF()
		ENDFOREACH()
	ENDIF()

	LIST(APPEND All ${LocalFixed})
	SOURCE_GROUP("${srcgrp}" FILES ${LocalFixed})
	
	FOREACH(S ${Local})
		IF(IS_DIRECTORY "${CMAKE_SOURCE_DIR}/${wd}/${S}")
			IF("${wd}" MATCHES "^[^\\/]+")
				SET(wd "${wd}/${S}")
			ELSE()
				SET(wd "${S}")
			ENDIF()

			LIST(APPEND pwd "${wd}")
			
			INCLUDE("${wd}/dir.cmake")
			DoSource()

			LIST(REMOVE_AT pwd -1)
			LIST(GET pwd -1 wd)
		ENDIF()
	ENDFOREACH()
ENDMACRO()

MACRO(StartSource src)
	SET(wd)
	SET(pwd "/")
	SET(testid 0)
	SET(Local ${src})
	DoSource()
ENDMACRO()
