CMAKE_MINIMUM_REQUIRED(VERSION 2.8.3)



INCLUDE(${CMAKE_TESTING_DIRECTORY}/tests.cmake)

ENABLE_TESTING()


FOREACH(file ${UnitTests})
	SET(target "UnitTest-${file}")
	
	ADD_EXECUTABLE(${target} ${CMAKE_TESTING_DIRECTORY}/Source/Unit/${file})
	
	SET_TARGET_PROPERTIES(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_TESTING_DIRECTORY}/Tests/Unit")
	SET_TARGET_PROPERTIES(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG "${CMAKE_TESTING_DIRECTORY}/Tests/Unit")
	SET_TARGET_PROPERTIES(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_TESTING_DIRECTORY}/Tests/Unit")
	SET_TARGET_PROPERTIES(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${CMAKE_TESTING_DIRECTORY}/Tests/Unit")
	SET_TARGET_PROPERTIES(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "${CMAKE_TESTING_DIRECTORY}/Tests/Unit")
	SET_TARGET_PROPERTIES(${target} PROPERTIES COMPILE_FLAGS "-I${CMAKE_TESTING_DIRECTORY}/Source -I${CMAKE_SOURCE_DIR}/Source")
	TARGET_LINK_LIBRARIES(${target} Gorgon)
	
	ADD_TEST(${file} ${CMAKE_TESTING_DIRECTORY}/Tests/Unit/${target})
ENDFOREACH()


FOREACH(file ${ManualTests})
	OPTION(MANUAL_TEST_${file} "Add ${file} manual tests to your manualtest run." OFF)
ENDFOREACH()

ADD_CUSTOM_TARGET(manualtest)

FOREACH(file ${ManualTests})
	IF(MANUAL_TEST_${file})
		SET(target "ManualTest-${file}")
		
		ADD_EXECUTABLE(${target} ${CMAKE_TESTING_DIRECTORY}/Source/Manual/${file})
		
		SET_TARGET_PROPERTIES(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_TESTING_DIRECTORY}/Tests/Manual")
		SET_TARGET_PROPERTIES(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG "${CMAKE_TESTING_DIRECTORY}/Tests/Manual")
		SET_TARGET_PROPERTIES(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_TESTING_DIRECTORY}/Tests/Manual")
		SET_TARGET_PROPERTIES(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${CMAKE_TESTING_DIRECTORY}/Tests/Manual")
		SET_TARGET_PROPERTIES(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "${CMAKE_TESTING_DIRECTORY}/Tests/Manual")
		SET_TARGET_PROPERTIES(${target} PROPERTIES COMPILE_FLAGS "-I${CMAKE_TESTING_DIRECTORY}/Source -I${CMAKE_SOURCE_DIR}/Source")
		TARGET_LINK_LIBRARIES(${target} Gorgon)
		
		ADD_CUSTOM_COMMAND(TARGET manualtest COMMAND ${CMAKE_TESTING_DIRECTORY}/Tests/Manual/${target})
	ENDIF()
ENDFOREACH()
