SET(Local
	../Audio.h
	Basic.h
	Audio.cpp
	
	Controllers.h
	Controllers.cpp
)

IF(AUDIOLIB STREQUAL "PULSE")
	LIST(APPEND Local PulseAudio.cpp)
	
	INCLUDE(${CMAKE_CURRENT_LIST_DIR}/FindPULSEAUDIO.cmake)
	#FIND_PACKAGE(PULSEAUDIO REQUIRED)
	
	LIST(APPEND Libs ${PULSEAUDIO_LIBRARY} ${PULSAUDIO_MAINLOOP_LIBRARY} pthread)
ENDIF()


IF(AUDIOLIB STREQUAL "WASAPI")
	LIST(APPEND Local WASAPI.cpp)
	LIST(APPEND Local WASAPI.inc.h)
ENDIF()